##  Probability Mass Functions

In [10]:
import numpy as np


| Term | Definition |
|------|-----------|
| normalized | A set of probabilities are normalized if they add up to 1. |
| probability mass function (PMF) | A function that represents a distribution by mapping each quantity to its probability. |

In this chapter we’ll introduce another way to describe a distribution, a probability mass function (PMF)

We’ll use Pmf objects to compute the mean and variance of a distribution, and the skewness, which indicates whether it is skewed to the left or right.

#### 3.1. PMFs

A Pmf object is like a FreqTab that contains probabilities instead of frequencies. So one way to make a Pmf is to start with a FreqTab.

In [11]:
from empiricaldist import FreqTab

ftab = FreqTab.from_seq([1, 2, 2, 3, 5])
ftab

1    1
2    2
3    1
5    1
Name: , dtype: int64

In [12]:
n = ftab.sum()
n

np.int64(5)

In [13]:
pmf = ftab / n
pmf

1    0.2
2    0.4
3    0.2
5    0.2
Name: , dtype: float64

This result indicates that 20% of the values in the sequence are 1, 40% are 2, and so on.

The probability we choose the value 1 is 0.2, the probability we choose the value 2 is 0.4

Because we divided through by n, the sum of the probabilities is 1, which means that this distribution is normalized.

A normalized FreqTab object represents a probability mass function (PMF), so-called because probabilities associated with discrete values are also called “probability masses”.

The empiricaldist library provides a Pmf object that represents a probability mass function, so instead of creating a FreqTab object and then normalizing it, we can create a Pmf object directly.

In [14]:
from empiricaldist import Pmf

pmf = Pmf.from_seq([1, 2, 2, 3, 5])
pmf

1    0.2
2    0.4
3    0.2
5    0.2
Name: , dtype: float64

In [15]:
pmf[2]

np.float64(0.4)

In [16]:
pmf[2] = 0.2
pmf(2)

np.float64(0.2)

You can modify an existing Pmf by incrementing the probability associated with a value:

In [17]:
pmf[2] += 0.3
pmf[2]

np.float64(0.5)

In [18]:
pmf[2] *= 0.5
pmf[2]

np.float64(0.25)

If you modify a Pmf, the result may not be normalized – that is, the probabilities may no longer add up to 1.

In [19]:
pmf.sum()

np.float64(0.8500000000000001)

The normalize method renormalizes the Pmf

In [20]:
pmf.normalize()

np.float64(0.8500000000000001)

In [21]:
pmf.copy()

1    0.235294
2    0.294118
3    0.235294
5    0.235294
Name: , dtype: float64

### 3.2. Summarizing a PMF

In [22]:
mean = np.sum(pmf.ps * pmf.qs)
mean

np.float64(2.7058823529411766)

In [23]:
pmf.mean()

np.float64(2.7058823529411766)